### ISSUE TITLE
chore(keymanweb): using 'kmw' as shorthand for 'keyman' is silly

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/help.keyman.com#1062]
https://help.keyman.com/developer/engine/web/current-version/guide/adding-keyboards

It is shorter, by 3 whole characters. But it is confusing and silly. Let's just use `keyman`!

**Comment by jahorton** [comment]
https://github.com/keymanapp/help.keyman.com/blob/master/developer/engine/web/17.0/reference/events/index.md

The Web event API does include use of the `kmw.` stuff as well... not that it's a part of the actual event names.  I don't think prefixing the `kmw.` bit would even work.  Meanwhile, the `osk.` bit stuff actually _does_ work if registering against keyman.addEventListener (rather than `keyman.osk.addEventListener`.

I've always felt a bit weird about the prefixes used in that section.  Do we just drop the `kmw.` ones?  Or do we make it `keyman.`, despite not actually using that prefix anywhere within the events?  My _personal_ preference would be to just make a bulleted list of `keyman` events and another of `keyman.osk` events.

**Comment by jahorton** [comment]
Also... it looks like the change has already been made for most of the 17.0 content.  Not for 16.0 content, though.

**Comment by mcdurdin** [comment]
> My _personal_ preference would be to just make a bulleted list of `keyman` events and another of `keyman.osk` events.

That sounds better to me.

> Also... it looks like the change has already been made for most of the 17.0 content (aside from event stuff). Not for 16.0 content, though.

OK, well if it's already done for 17.0, can close this issue -- no need to do the work also on 16.0 as the 17.0 content will be default very soon.
