### ISSUE TITLE
bug: broken links in linux 17 help

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/help.keyman.com#725]
```
Getting links from: http://localhost:8888/products/linux/[17](https://github.com/keymanapp/help.keyman.com/actions/runs/5171156000/jobs/9314525373#step:8:18).0/reference
├─BROKEN─ http://localhost:8888/products/linux/17.0/reference/km-config (HTTP_404)
├─BROKEN─ http://localhost:8888/products/linux/17.0/reference/km-kvk2ldml (HTTP_404)
├─BROKEN─ http://localhost:8888/products/linux/17.0/reference/km-package-get (HTTP_404)
├─BROKEN─ http://localhost:8888/products/linux/17.0/reference/km-package-install (HTTP_404)
├─BROKEN─ http://localhost:8888/products/linux/17.0/reference/km-package-list-installed (HTTP_404)
├─BROKEN─ http://localhost:8888/products/linux/17.0/reference/km-package-uninstall (HTTP_404)
```

Also noting that the title of the index page says "Keyman 16.0 for Linux Reference" instead of 17.0.

**Comment by mcdurdin** [comment]
These are still showing up as broken in current checks. Visit https://help.keyman.com/products/linux/17.0/reference/km-config for example

**Comment by ermshiperete** [comment]
I notice that when running `help-keyman-com.sh` (in build step 9 during a Release build on TC) we get an error: ["help2md: can't get `--help' info from ./km-package-get"](https://build.palaso.org/buildConfiguration/KeymanLinux_Master/388114?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&showLog=388114_5244_5244&logView=flowAware). 

I now modified how the build steps are called to match what we  do for test builds. We'll see if that is sufficient of if we have to modify `help-keyman-com.sh` as well to call `build.sh build` instead of `build-help.sh`.
